# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fc113ad4c9ff7c5023f3427b2bfbf8e4903f9d8c9a8aeb652b9f6fa42c36546b21384082b084291e48f3b9f8933f68e0a7193701ff4ff79302d558ba0ebe84b

test:
  secret_key_base: ba16375eec7f14cb6025ef239f71a24b32d1f304921f4222e61791da5d0389a5c5c84ff83d972acde39a7ebb66c3f73b165855d700868b6807af7c567b8a856d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
